name: hand2string
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - jupyter
  - ipykernel
  - ipywidgets
  - seaborn
  - pytorch
  - opencv
  - av
  - pandas
  - pyarrow
  - python-dotenv
  - pip:
      - "mediapipe>=0.10.14"
      - datasets
      - sacrebleu
      - huggingface_hub
      - "sentence-transformers<5"
      - transformers
      - wandb
