name: hand2string
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - jupyter
  - ipykernel
  - ipywidgets
  - seaborn
  - pytorch
  - opencv
  - pip:
      - mediapipe
      - datasets
      - sacrebleu
