name: hand2string
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytorch
  - opencv
  - av
  - pandas
  - pyarrow
  - python-dotenv
  - pip:
      - mediapipe
      - sacrebleu
      - huggingface_hub
      - "sentence-transformers<5"
